# Site settings
title: "하얀새"
subtitle: "'s 둥지"
name: "하얀새"
email: wjnam123@gmail.com
description:
url: "https://birdwhite.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
author:
street_address:
city:
state:
zip_code:
country: South Korea
phone: "(비공개)"

# Social settings
facebook_url: https://www.facebook.com/profile.php?id=100006695927582
github_url: https://github.com/BirdWhite
instagram_url: https://www.instagram.com/skadPtjd/
steam_url: https://steamcommunity.com/id/wjnam123/

instagram_id: skadPtjd

# Build settings
markdown: kramdown

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # 블로그 댓글 기능 true
      share: true
      related: true

plugins:
  - jekyll-paginate

# Outputting
permalink: /:categories/:title/
paginate: 10 # 첫 페이지에보여줄 최근 게시물 수를 지정
paginate_path: /blog/page:num/
timezone: Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
